// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeS7LNsSGSi0OKVp9oKKBnD8rwaciCOGI',
    appId: '1:981975569961:android:7a1b9d7831cdfccf106e38',
    messagingSenderId: '981975569961',
    projectId: 'lucasapp-b21db',
    databaseURL: 'https://lucasapp-b21db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lucasapp-b21db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-X_Psv3QJu_5NWLMIWauq9a6UzI8DjOc',
    appId: '1:981975569961:ios:3109dbe7ee8b5569106e38',
    messagingSenderId: '981975569961',
    projectId: 'lucasapp-b21db',
    databaseURL: 'https://lucasapp-b21db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lucasapp-b21db.firebasestorage.app',
    iosBundleId: 'com.example.lucasApp',
  );
}
